# Generated by Django 2.2.5 on 2019-11-15 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20191115_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingbook',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lendingbooks', to='mainapp.ContactBook'),
        ),
        migrations.AlterField(
            model_name='lendingbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendingbooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
