# Generated by Django 2.2.5 on 2019-11-15 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20191115_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingbook',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.ContactBook'),
        ),
    ]
