# Generated by Django 2.2.5 on 2019-11-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20191115_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingbook',
            name='action',
            field=models.CharField(choices=[('1', 'Lend'), ('2', 'Received')], max_length=1),
        ),
    ]
